### ISSUE TITLE
[MOVED] Conflict with mod Tiquality. #2458

### ISSUE THREAD

**Issue by TerminatorNL** [TerminatorNL/Tiquality#1]
Moved issue from [SpongeForge](https://github.com/SpongePowered/SpongeForge/issues/2458) to Tiquality

@Mr-Krab wrote:

> I am currently running   SpongeForge version:  1.12.2-2705-7.1.0-BETA-3460   Forge version: 14.23.4.2747   Java version: Java(TM) SE Runtime Environment (build 1.8.0_181-b13)   Operating System: Debian 9   Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI,  SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync,  EconomyLite, GriefPrevention, Holograms, HuskyCrates, HuskyUI,  LuckPerms, Nucleus, PlaceholderAPI, ProjectCore, QuestItemHelper,  SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest,  VirtualTool, Wasted, WorldEdit, spark   Mods (51): Minecraft, Minecraft Coder Pack, Forge Mod Loader,  Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Auto Crafter,  BiblioCraft, CoFH Core, CoFH World, CodeChicken Lib, Console Filter,  Construct's Armory, CraftTweaker JEI Support, CraftTweaker2,  CreativeCore, CreativeCoreDummy, CustomNPCs, Dungeon Mods, Ex Nihilo  Creatio, Fishing Net Mod, Hammer Core, HoloInventory, Immersive  Engineering, Immersive Tech, InstantUnify, Iron Chest, ItemPhysic, Just  Enough Items, LagGoggles, MTLib, Mantle, McJtyLib, Mekanism, Mod  Tweaker, MrCrayfish's Furniture Mod, Parachronology, Quick Leaf Decay,  Redstone Arsenal, Redstone Flux, Solar Flux Reborn, Thermal Dynamics,  Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers'  Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

> **Issue Description**

> The physics of liquids is blocked. Sometimes there are problems with  TileEntity. Сan do without this mod on the server, but then should  perhaps add its functionality to Sponge(optional). https://minecraft.curseforge.com/projects/tiquality The logs are clean. No error messages whith this problem.

> @TerminatorNL Problems are observed even with water and lava. These liquids are already in the white list.

**Comment by TerminatorNL** [comment]
@Mr-Krab, can you upload your config file and Tiquality version please?

**Comment by Mr-Krab** [comment]
@TerminatorNL Config https://pastebin.com/fHBnqAJF
Tiquality-FAT-1.12.2-ALPHA-0.4

**Comment by Mr-Krab** [comment]
@TerminatorNL Config https://pastebin.com/fHBnqAJF
Tiquality-FAT-1.12.2-ALPHA-0.4

**Comment by Mr-Krab** [comment]
[logs.zip](https://github.com/TerminatorNL/Tiquality/files/2427071/logs.zip)

**Comment by TerminatorNL** [comment]
Perhaps this is fixed in version 0.6-BETA. Possibly the same issue as #2 

Re-open this if needed
