### ISSUE TITLE
New (old) crash on starting server

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#11]
Full log:
[2018-12-22-2.log](https://github.com/TerminatorNL/Tiquality/files/2704336/2018-12-22-2.log)
Crash:
[crash-2018-12-22_00.30.03-server.txt](https://github.com/TerminatorNL/Tiquality/files/2704338/crash-2018-12-22_00.30.03-server.txt)

**Comment by TerminatorNL** [comment]
Fixed! 91920c8e8e77ce79016ac1ab8cd2b7b204a7a58d
