### ISSUE TITLE
Graves

### ISSUE THREAD

**Issue by MacWhinny** [TerminatorNL/Tiquality#13]
Hi, i've tested this on two servers, my local server and a hosted server and each one causes players to no longer be able to pick up their graves with the kay. I'm running the ATM3 Remix v 1.0.1 mod without sponge

**Comment by TerminatorNL** [comment]
Correct.

Stand on a grave and run /tq add feet

Graves need to be exempt from tick throttling in order to work

**Comment by MacWhinny** [comment]
Hi, so i did the command ingame and it worded. but only for a short time and others that come online and die can't get there grave back till i do the command over the grave

**Comment by TerminatorNL** [comment]
Intresting. Would you mind standing on a grave that does not function and run: `/tq debug` and copy-paste it's output?

**Comment by MacWhinny** [comment]
Unsure where  you're supposed to copy the info so took a screenshot https://imgur.com/gallery/1yoVaB0 It works after i've done the /tq add feet command but then someone else's will not be able to get theres. But it's not everyones

**Comment by TerminatorNL** [comment]
I have identified the problem, your screenshot helps alot.

**Comment by MacWhinny** [comment]
awesome. i look forwards to the next update >_<

**Comment by TerminatorNL** [comment]
Fixed in af897474f01caea22b967390928e6e24aa2fdaa6
