### ISSUE TITLE
Crash on creating/loading Single Player world

### ISSUE THREAD

**Issue by Andromander** [TerminatorNL/Tiquality#16]
Forge Version: 14.23.5.2786
Tiquality Version: FAT-1.12.2-BETA-0.9.3
Crash Log: https://gist.github.com/Andromander/9a9dfc1d0cbf0fec5b5d94a832ba13fa
Full Log: https://gist.github.com/Andromander/dc2aa3a20a9df961f9f9336a0d560f5a

----

### Steps to Reproduce:
1. With Tiquality installed, start a new single player world
2. After failing, attempt to load the world with Tiquality installed
3. Disable Tiquality, then reload the world once more

----

When attempting to create a new world or load a single player world with this mod installed, the result is this crash. The world that I tested was attempting to create it first, and then attempt to load it after it crashes when the world was being created. Disabling the mod and then attempting to load said world does not cause it to crash.

Though the circumstances of having Tiquality in a Single Player world would be somewhat counter intuitive, it does make creating an integrated server a little more difficult.

**Comment by P3rf3ctXZer0** [comment]
[crash-2019-01-25_06.02.28-server.txt](https://github.com/TerminatorNL/Tiquality/files/2795991/crash-2019-01-25_06.02.28-server.txt)

**Comment by TerminatorNL** [comment]
The world now loads. Thank you for the detailed report.

Please note that I have not yet thoroughly tested single player, if you encounter issues, please create a new issue!

**Comment by P3rf3ctXZer0** [comment]
alright thank you :D
