### ISSUE TITLE
[0.9.3] Tiquality crash with fake players

### ISSUE THREAD

**Issue by Electrofried** [TerminatorNL/Tiquality#17]
Tiquality is involved in a server crash when a player uses a fake player to perform an action, in this case it is an automated user from extra utilities. Have not tested other fake players yet though.

No plugins/sponge, mod list in crash log.
Crash log below.
[crash-2019-01-25_16.16.53-server.txt](https://github.com/TerminatorNL/Tiquality/files/2796933/crash-2019-01-25_16.16.53-server.txt)

**Comment by TerminatorNL** [comment]
I added extra measures: If no profile can be found, I return a dummy profile instead. (Commit 488969a6d68c55191148972d3e951b88517af2de)
