### ISSUE TITLE
WorldGuard support

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#19]
Would you like to introduce support for the import of WorldGuard regions in the mod?
This is very useful for Forge + Spigot servers.

**Comment by codydbgt** [comment]
LOL

**Comment by TerminatorNL** [comment]
I do not quite understand you fully, what kind of tracker did you have in mind in WorldGuard claims?

There are currently 3 tracker types implemented in Tiquality:
- Player (Player specific, a player is responsible for this)
- Forced (Admin claims, non-throttled areas)
- Deny (Blocks configured in config, never gets ticks)

For GriefPrevention and FTBUtilities this was easy, as getting the owner is simple.

Wouldn't it be easier to just make an admin claim using GriefPrevention if you wanted a non-throttled area?
