### ISSUE TITLE
Crash upon Server Load with SpongeForge & GriefPrevention

### ISSUE THREAD

**Issue by g0d-gam3** [TerminatorNL/Tiquality#26]
Forge: forge-1.12.2-14.23.5.2781-universal
Sponge: spongeforge-1.12.2-2768-7.1.5
GriefPrevention: griefprevention-1.12.2-4.3.0.689

Crash Log: https://pastebin.com/WR2Ct8v7

The server loads just fine without griefprevention and with tiquality and vice versa with no other plugins running.

**Comment by TerminatorNL** [comment]
Do you still have the full log?
