### ISSUE TITLE
???? -- randomly stop working

### ISSUE THREAD

**Issue by codydbgt** [TerminatorNL/Tiquality#3]
things like furnaces and xnet and possibly other TE will not tick for random players if u could add more debug info possibly 
consider adding me on discord ( Bucky420#1937 )  so i can help more :) 

what happened was i went to a players base and his furnace would not work but if i placed one it would work fine and yes i did check his /tq profile it was fine 

do note i had to remove the mod cause of this and in order to re add it i would need some sort of area based claiming probably a cuboid would be best as players do not understand or like when i have to add this and they must replace all there blocks or /tq claim i really want to use the mod hope we can get it working :)

**Comment by TerminatorNL** [comment]
Uninstalling Tiquality will result in loss of data on a per chunk basis.

Integration using other plugins like GriefPrevention are planned, aswell as shared blocks.

I have sent a request on discord. I might make a dedicated server for Tiquality.

**Comment by codydbgt** [comment]
can u resent that please :) i declined it thought u were a player
