### ISSUE TITLE
Tiquality ignoring settings.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TerminatorNL/Tiquality#30]
I set the minecraft weighted pressure plate to tick natural and it still doesn't work.

**Comment by P3rf3ctXZer0** [comment]
I did everthing via /command so I didn't misspell anything or get things wrong. I did use the feet syntax and it said sucessfully added but when you step on it - just remains unusable.

**Comment by P3rf3ctXZer0** [comment]
Forgive me for my very broken language - in a bit of a hurry.

**Comment by TerminatorNL** [comment]
Can you share:
* Your config file
* The exact command used in-game
* `/tq debug` output when standing on a weighted plate?

**Comment by P3rf3ctXZer0** [comment]
Yes I will re-add the mod so you can see for yourself. Its going to be a bit though.

**Comment by P3rf3ctXZer0** [comment]
Props tomorrow sometime.

**Comment by TerminatorNL** [comment]
That's fine. Take your time. I am swamped in deadlines for the next week. :+1:

**Comment by TerminatorNL** [comment]
If it's not too much to ask, do you have an update for me?

**Comment by P3rf3ctXZer0** [comment]
Okay no cause micro-cock basically knocked out my server and for the last 6 days after being gone for 8 I essentially have been playing pc doctor on my entire network.

**Comment by P3rf3ctXZer0** [comment]
I can test today.

**Comment by TerminatorNL** [comment]
That doesn't sound like fun, but thank you anyway!

**Comment by P3rf3ctXZer0** [comment]
Okay so nothing seems broken using release 1.5.2

**Comment by TerminatorNL** [comment]
All right, if you run into it again feel free to re-open this issue or create a new one!
