### ISSUE TITLE
New crash again

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#32]
SpongeForge 1.12.2-2838-7.1.7-RC3812
Tiquality-THIN-1.12.2-GAMMA-1.5.0

[debug.log](https://github.com/TerminatorNL/Tiquality/files/3320754/debug.log)

**Comment by TerminatorNL** [comment]
Can you also give me the latest.log?
I'm on mobile at the moment, and it is a bit easier to read.

If not, I'll take a look when I have access to a computer again

**Comment by TerminatorNL** [comment]
At first glance, it looks like an incompatibility with LagGoggles.

**Comment by TerminatorNL** [comment]
This bug actually isn't Tiquality, but LagGoggles: https://github.com/TerminatorNL/LagGoggles/issues/67

Because LagGoggles failed, Tiquality cannot inject into WorldServer.

Closing here, investigating LagGoggles.
