### ISSUE TITLE
Required - ClaimShare and UnclaimShare Commands 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TerminatorNL/Tiquality#36]
Alright so I have run into a new problem in 1.12.2 where when people want to live together and one person is offline half the base is basically offline. Can you please add a ClaimShare Command that allows you to keep the area working even when Allies are offline? Traversely you should also probably add UnclaimShare if you chose not to live with someone.

**Comment by TerminatorNL** [comment]
You can use [/tq share <playername>](https://github.com/TerminatorNL/Tiquality#commands-and-permissions).



> * /tq share <playername>
> 
>     *  Allows sharing tick time with basemates, meaning that you can keep playing if the base owner is offline. If both of you are online, the tick time is effectively doubled.
>     *  tiquality.use

**Comment by P3rf3ctXZer0** [comment]
Does not work as I needed.

**Comment by TerminatorNL** [comment]
Can you give an in-depth explanation of what you need?

**Comment by P3rf3ctXZer0** [comment]
Okay so after the previous issue we discussed this issue can stay closed.

**Comment by TerminatorNL** [comment]
All right. The issue we discussed is here: #37
(So other people know too)

**Comment by P3rf3ctXZer0** [comment]
yeah
