### ISSUE TITLE
[Bug] Crash server

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#39]
**Describe the bug**
Crash

**To Reproduce**
start server
**Which Forge version are you using?**
2838
**Which SpongeForge version are you using?**
1.12.2-2838-7.1.7-RC3848

[debug.txt](https://github.com/TerminatorNL/Tiquality/files/3417803/debug.txt)

**Comment by TerminatorNL** [comment]
```
[17:04:59] [main/INFO] [Tiquality-Boot]: I am designed for SpongeForge version: 1.12.2-2838-7.1.7-RC3812
[17:04:59] [main/WARN] [Tiquality-Boot]: SpongeForge version is different than expected!
[17:04:59] [main/WARN] [Tiquality-Boot]: This could result in undefined behavior.
[17:04:59] [main/WARN] [Tiquality-Boot]: 
[17:04:59] [main/WARN] [Tiquality-Boot]: Expected: '1.12.2-2838-7.1.7-RC3812', but you have: '1.12.2-2838-7.1.7-RC3848' installed.
```

Did you try the suggested version?

**Comment by bigenergy** [comment]
**spongeforge-1.12.2-2838-7.1.7-RC3843**
everything worked for me on this version, strange..

**Comment by TerminatorNL** [comment]
I try to make my mixins as 'compatible' with future versions as possible. But every once in a while the SpongeForge team makes big changes, which is impossible to comply with (I cannot look into the future)

**Comment by TerminatorNL** [comment]
I am compiling an updated version now, they have renamed classes and methods, that was an easy fix.

**Comment by TerminatorNL** [comment]
There you go: https://www.curseforge.com/minecraft/mc-mods/tiquality/files/2746092

**Comment by bigenergy** [comment]
sponge RC3856 
[deb.txt](https://github.com/TerminatorNL/Tiquality/files/3428958/deb.txt)

**Comment by bigenergy** [comment]
@TerminatorNL

**Comment by TerminatorNL** [comment]
Should be good now. Updated to latest Sponge (Again)
