### ISSUE TITLE
[Bug] removeInactiveTrackers crash

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#41]
**Describe the bug**
Crash server
**To Reproduce**
no info
**Which Forge version are you using?**
2838

**Which SpongeForge version are you using?**
spongeforge-1.12.2-2838-7.1.7-RC3870
Tiquality-THIN-1.12.2-GAMMA-1.5.6
[debug.log](https://github.com/TerminatorNL/Tiquality/files/3465035/debug.log)
[crash-2019-08-04_18.26.50-server.txt](https://github.com/TerminatorNL/Tiquality/files/3465036/crash-2019-08-04_18.26.50-server.txt)

**Comment by TerminatorNL** [comment]
Related to #20 and #22. For some reason I am not able to reproduce this, and I tried to counter this problem many times. I now resort to the dirtiest way to fix it: Catching the exception and print an error... At least then it wont crash any more.
