### ISSUE TITLE
Tiquality-THIN-1.12.2-GAMMA-1.6.1 Only 18.37KB [Question/Discussion]

### ISSUE THREAD

**Issue by zsn741656478** [TerminatorNL/Tiquality#42]
https://i.loli.net/2019/08/19/oEPGOy2b9WagHJj.png
Folders are empty.

**Comment by TerminatorNL** [comment]
Seems like my build was interrupted somehow.
Here's the properly built jar: [Tiquality-THIN-1.12.2-GAMMA-1.6.1.zip](https://github.com/TerminatorNL/Tiquality/files/3515642/Tiquality-THIN-1.12.2-GAMMA-1.6.1.zip). I'll update the Curse web page. Thank you for the report!
