### ISSUE TITLE
[Bug] PhaseState flood

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#43]
**Describe the bug**
PhaseState flood

**To Reproduce**
Start server

**Which Forge version are you using?**
tested on 14.23.5.2847 or 14.23.5.2838

**Which SpongeForge version are you using?**
1.12.2-2838-7.1.7-RC3924 or 1.12.2-2838-7.1.7-RC3902

[debug.txt](https://github.com/TerminatorNL/Tiquality/files/3655183/debug.txt)

**Comment by TerminatorNL** [comment]
Looks like an AE2 bug to me.
https://bt.industrial-craft.net/view.php?id=2610
Did you try to replicate it without Tiquality?

**Comment by bigenergy** [comment]
@TerminatorNL see https://github.com/SpongePowered/SpongeForge/issues/2981#issuecomment-535702277

**Comment by TerminatorNL** [comment]
Are you able to replicate this without Tiquality, though?

**Comment by bigenergy** [comment]
On my other server with the same mods, there are no tiquality and there is no this error.
The error occurs randomly and not always.

**Comment by TerminatorNL** [comment]
From what I have read about this error, a terraformer is attempting to change a block. This means it's related to your world (meaning your other server would not have had this issue anyways).

If the issue pops up again, figure out which player is loading a terraformer and find it in the world.
Then, temporarily disable Tiquality and see if the issue persists. I am 99.9% confident that this is just an IC2 bug, unrelated to Tiquality in any shape or form.
