### ISSUE TITLE
CC: Tweaked not functioning properly with TiQuality

### ISSUE THREAD

**Issue by idnthvn** [TerminatorNL/Tiquality#48]
Forge 2847 or even Forge 2838
Tiquality 1.72 FAT
Minecraft 1.12.2
Computercraft: Tweaked 1.86.0
Can replicate in client or on server.

Install mods
Start singleplayer or server
Place Mining Turtle
Give it a command (Excavate or Tunnel) and make sure there is fuel 
It will move very short and stop functioning.   Removing TiQuality allows them to function fine

**Comment by idnthvn** [comment]
I Fixed this by making Tiquality "ALWAYS_TICK" this block.  I noticed that WHEN the program starts, it looses the tracking on the block when the turtle moves in a direction. The turtle will "DANCE" since it stays in the same block. Soon as it starts moving, up, down, left, right, etc, the tracking gets lost

**Comment by TerminatorNL** [comment]
I'm glad you figured it out!
