### ISSUE TITLE
[Bug]Plant gatherer Leaf Decay causing ticking block exception with tiquality installed. 

### ISSUE THREAD

**Issue by MrNinja93** [TerminatorNL/Tiquality#49]
**Describe the bug**
This may or may not be tiquality based but the crashes don't happen without the mod installed so it's at the least compounding the problem. 

Server will crash on leaf decay from a IF plant gatherer tree farm

Leaves are set as natural blocks in the tiquality config just incase you ask

**To Reproduce**
Unclear, Plant gatherer from Industrial Foregoing and tree farm, one player's setup will crash the server as soon as it's operational but a test setup does not. possible the test farm was not large enough or similar.

**Which Forge version are you using?**
Forge 1.12.2-14.23.5.2847
**If you used the word 'error' somewhere, always provide the stack trace along with both _debug.log_ and _latest.log_**

Crashlog 
https://gist.github.com/MrNinja93/148716f5b2df1056e11afce796a4b5b8

**Comment by TerminatorNL** [comment]
Your error doesn't originate from Tiquality.
```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[oak, spruce, birch, jungle]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
```

The vanilla minecraft code is altered, as you can see here: `$StateImplementation.func_177229_b`. This is most likely another mixin mod or plugin.
