### ISSUE TITLE
Feature Request - Teams

### ISSUE THREAD

**Issue by dannydjdk** [TerminatorNL/Tiquality#5]
One of the main problems we have when using this mod is that if I am sharing a base with another player, some blocks are owned by me, and others by my base-mate. If only one of us is online, machines placed by the other tick very slowly (or not at all depending on configs and server load). I would love to be able to share ownership of blocks with other members of my team. Perhaps this could integrate with FTB Utilities or vanilla scoreboard teams.

**Comment by zwamdurkel** [comment]
Any ETA on this? I don't want to push you, but this is kind of important for server owners

**Comment by TerminatorNL** [comment]
Implemented!
**BE WARNED! Tiquality has a different world-save format!** Old versions are probably incompatible

**Comment by TerminatorNL** [comment]
If you wish to keep your world, hold off for a minute as I am solving this.

**Comment by TerminatorNL** [comment]
Commit 220450a80c5afa37ebf6ab2005ea2ce1281c1290 adresses this. (Version GAMMA-1.0.1)

Your old Tiquality data should be discarded, but you can use the new command /tq claim to import bases again.

Resizing your griefprevention claim or using FTBUtilities to temporarily unclaim and re-claim a chunk will also work.
