### ISSUE TITLE
[Bug] Not support the latest spongeforge

### ISSUE THREAD

**Issue by SettingDust** [TerminatorNL/Tiquality#50]
**Which Forge version are you using?**
forge-1.12.2-14.23.5.2847-universal
**Which SpongeForge version are you using?**
spongeforge-1.12.2-2838-7.1.9-RC3987
**Please provide the early startup messages starting with _[Tiquality-Boot]_**
https://paste.ubuntu.com/p/q2VKv5tNGg/

**Comment by NonToxicEel** [comment]
+1

**Comment by idnthvn** [comment]
+1
Im using  2847 forge and now the newest 7.1.10 version of sponge
the recommended 7.1.9 would be a great place, but the next in line after is 7.1.10 and works great.

Currently crash on startup with it now

**Comment by idnthvn** [comment]
i forked this and made updates to allow 7.1.10RC4000 sponge to work. unfortunatly i could not get it to build due to the repo being down atm

**Comment by dong031001** [comment]
> i forked this and made updates to allow 7.1.10RC4000 sponge to work. unfortunatly i could not get it to build due to the repo being down atm

It will be great if u may make a pull request toward this repo?

**Comment by TerminatorNL** [comment]
@idnthvn and @clienthax have adressed this issue in #53 (merged in d1a1e6a82584d8572ba5a30acb59dda9f873c6b6)
Thanks a ton!
