### ISSUE TITLE
Crash on Start SpongeForge

### ISSUE THREAD

**Issue by Mr-Krab** [TerminatorNL/Tiquality#6]
System: Debian 9
Java: Java(TM) SE Runtime Environment (build 1.8.0_191-b12)

SpongeAPI: 7.1.0-6eb292fd
Sponge: 1.12.2-7.1.5-SNAPSHOT
SpongeForge: 1.12.2-2768-7.1.5-RC3508
Minecraft Forge: 14.23.5.2770

Plugins (28): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, GuiShopManager, Holograms, HuskyCrates, HuskyUI, LuckPerms, Nucleus, PlaceholderAPI, ProjectCore, QuestItemHelper, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest, VirtualTool, Wasted, WorldEdit, spark

Mods (54): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Deadly Monsters, Ex Nihilo Creatio, Fishing Net Mod, Forestry, Hammer Core, HoloInventory, InstantUnify, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, MTLib, Mantle, McJtyLib, Mod Tweaker, MrCrayfish's Furniture Mod, Quick Leaf Decay, Redstone Arsenal, Redstone Flux, Solar Flux Reborn, SpongeForge, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

[latest.log](https://github.com/TerminatorNL/Tiquality/files/2659847/latest.log)

**Comment by TerminatorNL** [comment]
I am unable to replicate the issue, do you mind updating to Tiquality version 0.8.2 ?

**Comment by TerminatorNL** [comment]
Scratch that, I just updated it to 0.8.3, fixing another bug

**Comment by Mr-Krab** [comment]
[2018-12-09-4.log](https://github.com/TerminatorNL/Tiquality/files/2661476/2018-12-09-4.log)

**Comment by TerminatorNL** [comment]
Seems like the a version mismatch.

Tiquality has been compiled for:
Forge: 1.12.2-14.23.4.2705
SpongeForge 1.12.2-2705-7.1.0-BETA-3361

If it's not too much of a hastle, would it be possible for you to try these versions?

**Comment by Mr-Krab** [comment]
Unfortunately, this version is outdated and I cannot use it. Some mods will not allow the server to boot if I use the old version.

**Comment by TerminatorNL** [comment]
All right, I have simply removed the shadow method and turned to casting. I want to keep Tiquality working on as many versions as possible, and it seems like the getPos() shadow method caused this.

Committing now, awaiting CurseForge upload verification

**Comment by Mr-Krab** [comment]
Does not work(Version 1.12.2-BETA-0.8.7). I tried to start the server without Sponge, but the result is the same.
[latest.log](https://github.com/TerminatorNL/Tiquality/files/2668093/latest.log)
[debug.log](https://github.com/TerminatorNL/Tiquality/files/2668094/debug.log)

**Comment by TerminatorNL** [comment]
Oh I should have been more clear... The DEOBF files you can download from GitHub will not run in a server environment, these are the human-readable sources before they get obfuscated to allow them to run in Minecraft.

I have good news, however. I installed [0.8.8](https://minecraft.curseforge.com/projects/tiquality/files/2646575) on a StoneBlock server, and it seems to work here.

It's also wise to read the updated docs [README.MD](https://github.com/TerminatorNL/Tiquality/blob/master/README.md#i-just-installed-tiquality-and-the-tps-is-horrible). Importing existing worlds is not an easy task if you don't have GriefPrevention installed.

**Comment by TerminatorNL** [comment]
In the config you'll find this:
```cfg
    # Between ticks, the server must do some internal processing.
    # Increase this value if you see "can't keep up!" errors.
    # Try to keep this value as low as possible for performance.
    # Min: 0
    # Max: 2147483647
    I:TIME_BETWEEN_TICKS_IN_NS=90000
    D:WORLD_PLAYER_TICK_TIME_MULTIPLIER=0.1
```
This is dependent per-pack as larger modpacks usually require more time in between ticks to process data in the server thread. Having a few of these is not a problem, use this until you get no longer spammed by them.

And on another note: For throttling ticks, I think SpongeForge has a solution for that, Tiquality should not respect all SpongeForge's tick throttling.
