### ISSUE TITLE
Feature Request - Claim Chunks

### ISSUE THREAD

**Issue by dannydjdk** [TerminatorNL/Tiquality#7]
When adding this mod to an existing world, it's overwhelming to have to break and replace every tile entity or stand above and run /tq track on every one. It would be great to be able to run a command that "claims" all of the tile entities within the chunk. Perhaps even better would be integration with FTB Utilities chunk claiming such that all tile entities within my claims would automatically be owned by me. I believe this is similar to what you're doing with GriefPrevention(?).

**Comment by TerminatorNL** [comment]
That is indeed what I am doing with GriefPrevention, the main problem is that I have to prevent players claiming blocks they do not own, potentially breaking their setup. That's why I am hooking into protection plugins, to prevent that :+1:

**Comment by TerminatorNL** [comment]
Welp, I forgot to mention that this is totally planned.

**Comment by Electrofried** [comment]
Seconded the request for support for FTBU integration. One thing I love about your mods is the forge support. So many utilities for server admins require sponge and this can cause all sorts of secondary issues with forge mods.  
FTBU is THE most widely used grief prevention, claiming, and chunk loading system in the forge ecosystem.   If there is any way you could pull the existing data from FTB teams and claimed chunks to integrate with this it would make many a 'forge only' server admin super happy .

**Comment by TerminatorNL** [comment]
Behold: Support is here!
