### ISSUE TITLE
Error after /tq import_griefprevention

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#8]
Tiquality-THIN-1.12.2-BETA-0.8.9
I use /tq import_griefprevention

Log: line 52491
[new2.log](https://github.com/TerminatorNL/Tiquality/files/2677631/new2.log)

**Comment by TerminatorNL** [comment]
It was unable to import a claim, because the UUID of the owner does not exists in Forge's cache.
It did, however import the rest of your claims. Just keep an eye out for that one single claim that did not work

**Comment by TerminatorNL** [comment]
This does, however need a closer look.

**Comment by Alexandrea** [comment]
We have same error but crashing on startup its happening on some modpacks but other modpacks seems to be fine

Tiquality-THIN-1.12.2-BETA-0.8.9.jar

full log but pretty much same error
https://gist.github.com/Alexandrea/2364688dc6ae6e349f94b196d6a40fdb

**Comment by TerminatorNL** [comment]
I have released version 0.8.10, that should account for the missing player profiles. Please note that if you have an extremely special case it may still fail (to see if it actually happens).
Please re-open if the problem persists after 0.8.10
